### ISSUE TITLE
no cities found

### ISSUE THREAD

**Issue by dbolton** [Sparker0i/Weather#1]
Steps to reproduce
1 open simple weather for first time
2 when it asks for a city, type: New York

Expected behavior: it should show a weather report

Actual behavior: it says "city not found"

**Comment by Sparker0i** [comment]
Did you download the app from the Play Store or did you build the app by cloning this repo and testing with New York?

**Comment by dbolton** [comment]
I downloaded version 3 from f-droid

**Comment by Sparker0i** [comment]
Yep, now got the root of this error. Seems like signing the app caused proguard to be activated. This has been fixed in 3.0.1 which will be available soon as an update over there

**Comment by dbolton** [comment]
Wonderful. Thank you
