### ISSUE TITLE
Imperial units on weather graphs

### ISSUE THREAD

**Issue by MarcusLlewellyn** [Sparker0i/Weather#15]
It would be nice if the weather graphs and forecast details could use units more familiar to my country. Miles per hour, bars, and inches are all units we're accustomed to.

**Comment by Sparker0i** [comment]
Hey there,

Thanks for reporting this. I just came to know of this. I'll surely look into it.

Regards.

**Comment by Sparker0i** [comment]
https://github.com/Sparker0i/Weather/commit/cb3b5968724f2eeebae27c6b94b2ae8dc5218ebc

**Comment by Sparker0i** [comment]
Fixed in the commit mentioned above
