### ISSUE TITLE
rendering issues when closing and re-opening the app. 

### ISSUE THREAD

**Issue by n33l33m3lj** [Sparker0i/Weather#19]
![tmp_22984-screenshot_2017-06-25-01-43-151807274645](https://user-images.githubusercontent.com/19912122/27512655-4ca4ebc0-5948-11e7-8b55-7b2fa5413eb1.png)

Device: LG g flex 2
App version: 4.1

**Comment by Sparker0i** [comment]
Hey there,

I need more information on this.
1. Which version of the app are you using?
2. How are you triggering this behaviour?
3. Are you changing the DPI of your screen then reopening the app?

**Comment by n33l33m3lj** [comment]
The problem only seems to happen when opening the app via the widget.

**Comment by n33l33m3lj** [comment]
I downloaded it from F-Droid.

No, I haven't changed the DPI.

**Comment by pnewby060** [comment]
Ok I've recreated it by increasing font size while activity in recents. When you resume the activity with the new font size or even dpi settings somehow the parts of the app that can scroll seem to make a new one above it and keep the old layout frozen where it was from the first launch.

![screenshot_20170625-094422](https://user-images.githubusercontent.com/9244321/27514759-dd5294cc-598b-11e7-8a16-4bd7b7e59159.png)

**Comment by Sparker0i** [comment]
@pnewby060 Yes I am aware of that thing happening when the font size or the display size is changed. That is a known bug indeed. But what @n33l33m3lj says is that he hasn't changed his DPI whatsoever. Testing here with both Large and Small Widget - on a custom ROM and on a stock ROM worked fine for me. I have no idea on how @n33l33m3lj has triggered it then.
