### ISSUE TITLE
Settings for units

### ISSUE THREAD

**Issue by Jan02** [Sparker0i/Weather#21]
A setting for wind speed units would be great.
kilometer per sec.
meter per sec.
mile per sec.

Could be grouped with the Celsius/Fahrenheit setting.

**Comment by Sparker0i** [comment]
Hey there,

m/s and mil/h is already combined with Celsius/Fahrenheit setting.

Regarding other modes, I'm planning a Settings screen in the next update, where multiple options will be available.

**Comment by Jan02** [comment]
What if you want to use Fahrenheit with m/s ? The settings screen will be welcome.

**Comment by Sparker0i** [comment]
Yeah, that settings screen is planned for the next update

**Comment by paulle** [comment]
Please add for wind speed the option km/h because people in some countries can better imagine the windspeed with this unit and they don't have to calculate from m/s to km/h.

**Comment by Sparker0i** [comment]
I will surely work on this when I'm free. Right now I am busy with other projects, so I may take time to release the next version of Simple Weather

**Comment by paulle** [comment]
Thank you

Am 22. März 2018 13:17:00 MEZ schrieb Aaditya Menon <notifications@github.com>:
>I will surely work on this when I'm free. Right now I am busy with
>other projects, so I may take time to release the next version of
>Simple Weather

-- 
K-9 Mail

**Comment by Sparker0i** [comment]
@sniperle Thanks for your suggestion. As I said I am busy with other things, so I will do this only in the next major update. If you don't mind, could you put another issue for it.

**Comment by sniperle** [comment]
@Sparker0i OK, I opened #40 and don't hurry, take your time ;-)

**Comment by Sparker0i** [comment]
We can continue in #51
