### ISSUE TITLE
Saved locations

### ISSUE THREAD

**Issue by kRYOoX** [Sparker0i/Weather#24]
Here's an idea for an improvement: saved locations.

I often look for weather from Paris, FR, and Stockholm, SE. As it is today, I have to manually look them up every time I open the app.

I see that swiping from the right edge to the left doesn't do anything. It could be assigned to cycling through multiple saved locations quickly.

**Comment by Sparker0i** [comment]
Hey there,

I am planning this for the next feature update

**Comment by Sparker0i** [comment]
Hey there,

This feature is available in the latest commits (though not in the Swipe from right to left form) and it resides in the Drawer.
