### ISSUE TITLE
using android with bigger font size letters are cutted in simple weather

### ISSUE THREAD

**Issue by paulle** [Sparker0i/Weather#3]
Using android with bigger font size letters are cutted in simple weather. See first screenshot.
![screenshot_20170420-154951](https://cloud.githubusercontent.com/assets/4852079/25236303/d6bc7e7a-25e7-11e7-949f-74576fd5116f.png)
![screenshot_20170420-154924](https://cloud.githubusercontent.com/assets/4852079/25236304/d6c2dca2-25e7-11e7-9ed8-709160146a10.png)

**Comment by Sparker0i** [comment]
I am working on updated layouts of the home weather screen for multiple screen sizes. After finishing that work, I will consider giving this a thought.

Regards.

**Comment by pnewby060** [comment]
I have created a pull request #5 regarding this issue, this is my first time contributing to a project so apologies if I am doing it wrong. Any advice for future reference about contributing would be greatly appreciated.

Thank you.
