### ISSUE TITLE
simple widget location stuck on London, GB

### ISSUE THREAD

**Issue by fermulator** [Sparker0i/Weather#30]
Good day,

New user here. Found via Fdroid.

Installed onto BlackBerry priv.
Searched for city: "London, CA"
 , found it. The main app link works.

But if one adds the simple whether widget to the main panel, it showed as null for a moment, then my city (yay), but then defaulted back to "London, GB" (boo)

In this test, the user does not want to share their location always with the app. Search for city, retain that city. Only when travelling perhaps they would enable location access.

**Comment by Sparker0i** [comment]
Hey there,

Thanks for informing this. It has already been fixed in one of the commits
here which should make it to you in the next update.

**Comment by fermulator** [comment]
@Sparker0i ; which commit? - tie this issue to that, and mark as fixed/closed?

**Comment by Sparker0i** [comment]
I don't know which one. The problem was the code was only saving the city name, even if you entered the country code. I had made this correction, but seems it is deep in one of those commits.

Anyways it has been fixed already
