### ISSUE TITLE
Widget "sticks" at wrong location and doesn't update 

### ISSUE THREAD

**Issue by ithink314** [Sparker0i/Weather#31]
This looks similar to other report, but may be not identical.

Using simple weather version 4.1 from fdroid. On nexus 6 with custom lineage 15.0 rom...

Physically in Richmond, VA, in app, location button works, it seems. Shows "Richmond, US". But widget shows Richmond, CA, and does not appear to update when touching circle with arrow. Also, search for location Richmond goes direct to Richmond, CA; no option for Richmond, VA. Similar in other locations with multiple state choice, it just picks one "US".

**Comment by Sparker0i** [comment]
Hey there,

Please try v5. That bug should have been fixed there. If it is still not working for you, logcats should help me out
