### ISSUE TITLE
Danish translation info

### ISSUE THREAD

**Issue by twikedk** [Sparker0i/Weather#32]
I have made a Danish translation but as not being a reviewer I'm not able to close it.

**Comment by Sparker0i** [comment]
Did you do the translation on transifex?

**Comment by twikedk** [comment]
Yes but you don't get any information that it has been done?

**Comment by twikedk** [comment]
I have translated and reviewed the translation but I'm not sure if Transifex let's you know it it's finished?

**Comment by Sparker0i** [comment]
No notifications for me. I have to manually check everytime.

**Comment by twikedk** [comment]
OK if I make update to the file should I post a new issue here then? Just to make it easier for you.

**Comment by Sparker0i** [comment]
Yeah, either that or a pull request should do

**Comment by twikedk** [comment]
Now I'm not sure what you mean by a pull request? I opened #39 to make a pull request on the updated danish translation already done on transifex but you replied that all translation should be done in transifex, so how to make you aware of an updated version then??
