### ISSUE TITLE
Screen rotation while settings are displayed

### ISSUE THREAD

**Issue by spocko** [Sparker0i/Weather#37]
Simple Weather 5.3 on Android 6.0.1:
If the screen is rotated while the settings menu is displayed, then the screen starts flickering and redrawing repeatedly. Must kill the app to recover. This is repeatable every time.

1. Make sure screen rotation is enabled in device settings 
2. Hold device in portrait orientation
3. Open Simple Weather
4. Open hamburger menu
5. Tap settings to open the Settings menu
6. Rotate device to landscape orientation
7. Screen starts flickering repeatedly, can't back out of settings

**Comment by Sparker0i** [comment]
Strange. Nothing here on either Android 5.1 or 8.1 . Which phone are you
using BTW?

**Comment by Sparker0i** [comment]
Any GIFs or video so that I could help 😃

**Comment by spocko** [comment]
Samsung Galaxy Note 4 on stock Samsung ROM. The procedure in the first post triggers the problem every time. It also happened to me once when screen rotation was turned off, but I haven't been able to reproduce that.

**Comment by Sparker0i** [comment]
Hey there,

Can you please post a video/GIF or something? I am unable to reproduce it here on a variety of devices (Redmi Note 3 on Android 8.1, Redmi Note 4 on 7.0, Lenovo P1m on 5.1, Moto G3 on 6.0)

**Comment by spocko** [comment]
Strange. The issue occurs on all of my devices. Galaxy Note 4 on 6.0.1, Nexus 7 2013 on 6.0.1, Nexus 7 2012 on 5.1.1, LG V20 on 7.0. I'm not sure how a video would help. The first post lists the exact steps to reproduce the issue on all the devices that I mentioned.

**Comment by spocko** [comment]
Another observation: If I open Simple Weather while my screen is in landscape orientation, then the app exits/crashes immediately.

**Comment by Sparker0i** [comment]
Hey there, this should have been fixed with the latest commit, as I did discover the root cause (It was fixed in the previous commit btw). Sorry for keeping this inactive, as I was busy with academics :)
