### ISSUE TITLE
Problem building v5.0 in F-Droid

### ISSUE THREAD

**Issue by tomas-chrastina** [Sparker0i/Weather#38]
Hello,

as far as I can see, there's problem with building version 5 in [F-Droid](https://f-droid.org/wiki/page/com.a5corp.weather/lastbuild_642). Can you please check it out?

Thank you in advance.

--
Best regards,
Tomas.

**Comment by Sparker0i** [comment]
Hey there,

The very same problem existed before in Travis CI too. But I solved it by adding some lines of code in my gradle config files. Don't know why is it happening like that on FDroid. Meanwhile you can download from XDA Labs or the Play Store too

**Comment by Sparker0i** [comment]
And moreover I have release 5.3.2 in the releases. Are you sure it is happening there too?

**Comment by tomas-chrastina** [comment]
Hello,

I checked version v5.3.2 and it looks fine -> [5.3.2 (version code 656)](https://f-droid.org/wiki/page/com.a5corp.weather)

Thank you for all your work!

PS: Generally I prefer F-Droid over Google Play. So I'll rather wait for correct build there.

--
Best regards,
Tomas.
