### ISSUE TITLE
The application crashes when first open it in landscape mode

### ISSUE THREAD

**Issue by ahyar92** [Sparker0i/Weather#42]
#### Expected behavior
Supposedly, When I open the app in a skewed rotation (landscape mode), the application will not run into any problems, because the application does not support landscape mode at all.

#### Actual behavior
Initially, my smartphone was in a tilted position (Landscape), and I accidentally opened the app, and suddenly the app crashes and bounces out. Next, I try to do the same thing by opening the app with smartphone position in the landscape, and the error still occurs.

#### How to reproduce
1. Install the application first
2. Make sure the <code>Auto Rotate</code> on smartphone is turned on
3. Next, tilt the smartphone in landscape, then open the app. 
*Then you will find the error as I experienced*

----
- Device: Xiaomi Redmi 4X
- Operating system: Marshmallow, 6.0.1 mmb29m (CPU: Octa-core Max 1.9 GHz, RAM: 2 GB)
- Application Version:  	5.3.2 

#### Recording Of The Bug
https://www.youtube.com/watch?v=kY1VIMyBjkM

#### Logcat
```
--------- beginning of crash
05-21 22:52:22.666 11595 11595 E AndroidRuntime: FATAL EXCEPTION: main
05-21 22:52:22.666 11595 11595 E AndroidRuntime: Process: com.a5corp.weather, PID: 11595
05-21 22:52:22.666 11595 11595 E AndroidRuntime: java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{e087ebf V.E...... R......D 0,0-712,286} not attached to window manager
05-21 22:52:22.666 11595 11595 E AndroidRuntime: 	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:430)
05-21 22:52:22.666 11595 11595 E AndroidRuntime: 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:356)
05-21 22:52:22.666 11595 11595 E AndroidRuntime: 	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:118)
05-21 22:52:22.666 11595 11595 E AndroidRuntime: 	at android.app.Dialog.dismissDialog(Dialog.java:365)
05-21 22:52:22.666 11595 11595 E AndroidRuntime: 	at android.app.Dialog$1.run(Dialog.java:135)
05-21 22:52:22.666 11595 11595 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:742)
05-21 22:52:22.666 11595 11595 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-21 22:52:22.666 11595 11595 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-21 22:52:22.666 11595 11595 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5527)
05-21 22:52:22.666 11595 11595 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-21 22:52:22.666 11595 11595 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
05-21 22:52:22.666 11595 11595 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
05-21 22:52:22.672 11595 11595 E MQSEventManagerDelegate: failed to get MQSService.
```

**Comment by Sparker0i** [comment]
This has been fixed with the latest commit. Thanks for reporting, and sorry for not having a look into this earlier, as I was busy with academics :)
