### ISSUE TITLE
weather maps question

### ISSUE THREAD

**Issue by paulle** [Sparker0i/Weather#7]
For first v0.31from fdroid is working fine. Thank you. But don't understand the wetter maps. Rain,wind, temperature is always the same map tainted in grey, green or orange. I can't see any additional information in these maps. Maybe I'm too stupid, but I see only a normal map with tainting.

**Comment by paulle** [comment]
Edit: I was too stupid. One can only see the weather information on the map, when scaling up.

**Comment by Sparker0i** [comment]
Hey there,

The weather maps have 3 options: Rain, Wind and temperature. Each one of them has its own color of representation on the map : Blue , Green and Orange

If the area in focus on the map has a darker blue shade, that means it has a chance of high precipitation in the next few hours than the areas with lighter blue shade or no shade (white/transparent , location is clearly visible without the blue overlay)

Similarly you can apply this logic for Wind tab as well. An area with a darker green shade means that area is having a greater wind speed over an area with a lighter green overlay/no overlay. In a similar way, you can think about the temperature tab too.

Regards.
